#! /bin/bash
###
## Bonding Slave Network Device Setup Script
## Copyright (C) 2012  Kyle Moffett <kyle@moffetthome.net>
##
## This program is free software; you can redistribute it and/or modify it
## under the terms of version 2 of the GNU General Public License, as
## published by the Free Software Foundation.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
## for more details.
##
## You should have received a copy of the GNU General Public License along
## with this program; otherwise you can obtain it here:
##   http://www.gnu.org/licenses/gpl-2.0.txt
###

## Throw up our hands and give up on errors
set -e

## If "bond-slave-to" isn't set in this interfaces config then ignore it
[ -n "${IF_BOND_SLAVE_TO+set}" ] || exit 0

case "${IFACE}" in
*:*)
	echo "Cannot make a bonding slave from an alias: ${IFACE}" >&2
	exit 1
	;;
esac

## Make sure the interface exists first
if ! ip link show dev "${IFACE}" >/dev/null 2>&1; then
	echo "Nonexistent bonding slave device: ${IFACE}" >&2
	exit 1
fi
if ! ip link show dev "${IF_BOND_SLAVE_TO}" >/dev/null 2>&1; then
	echo "Nonexistent bonding master device: ${IFACE}" >&2
	exit 1
fi

## Remove it from the bond
echo "-${IFACE}" >"/sys/class/net/${IF_BOND_SLAVE_TO}/bonding/slaves"

## Turn the interface off and clean up the flags
ip link set dev "${IFACE}" down	\
	arp on			\
	dynamic off		\
	multicast off		\
	allmulticast off

## Flush addresses
ip addr flush dev "${IFACE}" 2>/dev/null
sysctl "net.ipv6.conf.${IFACE}.autoconf"=1
sysctl "net.ipv6.conf.${IFACE}.dad_transmits"=1
