#! /bin/bash
###
## DHCP Network Device Setup Script
## Copyright (C) 2012  Kyle Moffett <kyle@moffetthome.net>
##
## This program is free software; you can redistribute it and/or modify it
## under the terms of version 2 of the GNU General Public License, as
## published by the Free Software Foundation.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
## for more details.
##
## You should have received a copy of the GNU General Public License along
## with this program; otherwise you can obtain it here:
##   http://www.gnu.org/licenses/gpl-2.0.txt
###

## Throw up our hands and give up on errors
set -e

## If "dhcp-custom" isn't set in this interfaces config then ignore it
[ -n "${IF_DHCP_CUSTOM+set}" ] || exit 0

case "${IFACE}" in
*:*)
	echo "Cannot run DHCP from an alias: ${IFACE}" >&2
	exit 1
	;;
esac

## Make sure the interface exists first
if ! ip link show dev "${IFACE}" >/dev/null 2>&1; then
	echo "Nonexistent DHCP device: ${IFACE}" >&2
	exit 1
fi

## Start the dhclient
dhclient -v ${IF_DHCP_CUSTOM} \
	-pf "/var/run/dhclient.${ADDRFAM}.${IFACE}.pid" \
	-lf "/var/lib/dhcp/dhclient.${ADDRFAM}.${IFACE}.leases" \
	${IFACE}
