#! /bin/bash
###
## Software Bridging Teardown Script
## Copyright (C) 2006       Kyle Moffett <kyle@moffetthome.net>
## Copyright (C) 2007-2011  eXMeritus, A Boeing Company
##
## This program is free software; you can redistribute it and/or modify it
## under the terms of version 2 of the GNU General Public License, as
## published by the Free Software Foundation.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
## for more details.
##
## You should have received a copy of the GNU General Public License along
## with this program; otherwise you can obtain it here:
##   http://www.gnu.org/licenses/gpl-2.0.txt
###

## Throw up our hands and give up on errors
set -e

## Only delete the interface if it's not an alias
case "${IFACE}" in
*:*)
	exit 0
	;;
esac

## If it doesn't exist then just ignore it and exit
ip link show "${IFACE}" >/dev/null 2>&1 || exit 0

## Only try to tear down the bridge interface if we could have created it
[ -z "${IF_BRIDGE_DEVS+set}" ] && exit 0

## Ensure that it's actually a bridge
[ -d "/sys/class/net/${IFACE}/bridge" ] || exit 0

## Oh, we should probably make sure that bridging tools are installed first
if ! [ -x /usr/sbin/brctl ]; then
	cat >&2 <<EOF
Err... You've got what appears to be a completely *IMPOSSIBLE* configuration.
It looks like "${IFACE}" is configured as a bridge interface, but you don't
seem to have the bridging tools installed (EG: The Debian "bridge-utils"
package).  Did you delete them?

EOF
	exit 1
fi

## Finally!!!
brctl delbr "${IFACE}"
