#! /bin/bash
###
## VLAN Teardown Script
## Copyright (C) 2006       Kyle Moffett <kyle@moffetthome.net>
## Copyright (C) 2007-2011  eXMeritus, A Boeing Company
##
## This program is free software; you can redistribute it and/or modify it
## under the terms of version 2 of the GNU General Public License, as
## published by the Free Software Foundation.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
## for more details.
##
## You should have received a copy of the GNU General Public License along
## with this program; otherwise you can obtain it here:
##   http://www.gnu.org/licenses/gpl-2.0.txt
###

## Throw up our hands and give up on errors
set -e

## Only delete the interface if it's not an alias
case "${IFACE}" in
*:*)
	exit 0
	;;
esac

## If it doesn't exist then just ignore it and exit
ip link show "${IFACE}" >/dev/null 2>&1 || exit 0

## Only try to destroy the VLAN interface if we could have figured out how to
## create it
case "${IFACE}" in
?*.[0-9]|?*.[0-9][0-9]|?*.[0-9][0-9][0-9]|?*.[0-9][0-9][0-9][0-9])
	: ## The device even looks VLAN-ish, so it's OK to destroy it
	;;
vlan[0-9]|vlan[0-9][0-9]|vlan[0-9][0-9][0-9]|vlan[0-9][0-9][0-9][0-9])
	## Make sure we have a valid device to attach it to
	[ -n "${IF_VLAN_DEV}" ] || exit 0
	;;
*)
	## Need both vlan-dev and vlan-id
	[ -n "${IF_VLAN_DEV}" -a -n "${IF_VLAN_ID}" ] || exit 0
	;;
esac

ip link delete dev "${IFACE}" type vlan id "${IF_VLAN_ID}"
